export const chapters = [
  {
    standard: "Class 6",
    chapters: [
      {
        chapterNo: 1,
        section: "Fundamental",
        title: "Let’s meet our techno friends",
        author: "Mr.S. Ganesh",
      },
      {
        chapterNo: 2,
        section: "Fundamental",
        title: "Let’s play with BOSS",
        author: "Mr.S. Ganesh",
      },
      {
        chapterNo: 3,
        section: "Fundamental",
        title: "Your Keyboard, Your Power",
        author: "Mr.S. Ganesh",
      },
      {
        chapterNo: 4,
        section: "Fundamental",
        title: "Your Keyboard, Your Power",
        author: "Mr.S. Ganesh",
      },
      {
        chapterNo: 5,
        section: "Fundamental",
        title: "Use the mouse win the race",
        author: "Mr.S. Ganesh",
      },
      {
        chapterNo: 6,
        section: "Online Tools",
        title: "PSchool",
        author: "Mr.R.K.Muralidharan",
      },
      {
        chapterNo: 7,
        section: "Online Tools",
        title: "Stellarium",
        author: "Mr.S. Ganesh",
      },
      {
        chapterNo: 8,
        section: "Online Tools",
        title: "Anatomy Explorer",
        author: "Mr.R.K.Muralidharan",
      },
      {
        chapterNo: 9,
        section: "AI",
        title: "AI Intro",
        author: "Mr.S.Dhilip",
      },
      {
        chapterNo: 10,
        section: "AI",
        title: "Voice Image Searching",
        author: "MR. PRABHAKAR",
      },
      {
        chapterNo: 11,
        section: "AI",
        title: "Autodraw",
        author: "MR. PRABHAKAR",
      },
      {
        chapterNo: 12,
        section: "AI",
        title: "Image generation",
        author: "Mr.S.Dhilip",
      },
      { chapterNo: 13, section: "AI", title: "Music", author: "Mr.S.Dhilip" },
      {
        chapterNo: 14,
        section: "Geogebra",
        title: "Line",
        author: "Mr. Kasiraja",
      },
      {
        chapterNo: 15,
        section: "Geogebra",
        title: "Trace&Animation",
        author: "Dr.BJ.Murali",
      },
      {
        chapterNo: 16,
        section: "Geogebra",
        title: "Angles",
        author: "Mr. A.Kasivijayan",
      },
      {
        chapterNo: 17,
        section: "Coding",
        title: "Blockly",
        author: "Mr.V.Lazar Ramesh",
      },
      {
        chapterNo: 18,
        section: "Coding",
        title: "Blockly",
        author: "Mr.V.Lazar Ramesh",
      },
      {
        chapterNo: 19,
        section: "Coding",
        title: "Blockly",
        author: "Mr.V.Lazar Ramesh",
      },
      {
        chapterNo: 20,
        section: "Coding",
        title: "Turtle Art - Interface",
        author: "Mrs.N.Kalpana",
      },
      {
        chapterNo: 21,
        section: "Coding",
        title: "Turtle Art - Moving the turtle",
        author: "Mr.Anandhakanaan",
      },
      {
        chapterNo: 22,
        section: "Coding",
        title: "Turtle Art - Drawing basic shapes",
        author: "Mrs.N.Kalpana",
      },
      {
        chapterNo: 23,
        section: "Coding",
        title: "Turtle Art - Introduction to loops",
        author: "Mr.M.Maria Anthuvan",
      },
      {
        chapterNo: 24,
        section: "Coding",
        title: "Turtle Art - Pen blocks",
        author: "Mr .J.Senthil selvan",
      },
      {
        chapterNo: 25,
        section: "Coding",
        title: "Turtle Art - Assignment",
        author: "Mr.Anandhakanan",
      },
    ],
  },
  {
    standard: "Class 7",
    chapters: [
      {
        chapterNo: 1,
        section: "Fundamental",
        title: "Draw your dreams",
        author: "Mr.S.Ganesh",
      },
      {
        chapterNo: 2,
        section: "Fundamental",
        title: "Let Your Words Flow-1",
        author: "Mr.S.Ganesh",
      },
      {
        chapterNo: 3,
        section: "Fundamental",
        title: "Let Your Words Flow-2",
        author: "Mr.S.Ganesh",
      },
      { chapterNo: 4, section: "Online Tools", title: "PHET", author: "" },
      {
        chapterNo: 5,
        section: "Online Tools",
        title: "Game to Learn English",
        author: "R.K.Muralidharan",
      },
      {
        chapterNo: 6,
        section: "Online Tools",
        title: "Google Earth",
        author: "R.K.Muralidharan",
      },
      {
        chapterNo: 7,
        section: "AI",
        title: "Image generation",
        author: "MR PRABHAKAR",
      },
      {
        chapterNo: 8,
        section: "AI",
        title: "Article & Story Creation",
        author: "MR PRABHAKAR",
      },
      {
        chapterNo: 9,
        section: "AI",
        title: "Mindmap",
        author: "MR PRABHAKAR",
      },
      {
        chapterNo: 10,
        section: "AI",
        title: "Translator",
        author: "MR DHILIP",
      },
      {
        chapterNo: 11,
        section: "Geogebra",
        title: "Picture to Video",
        author: "MR DHILIP",
      },
      {
        chapterNo: 12,
        section: "Geogebra",
        title: "Geometry - Types of Triangle",
        author: "Mr.Kasiraja",
      },
      {
        chapterNo: 13,
        section: "Geogebra",
        title: "Measurement Area & Perimeter",
        author: "Mr.A.Kasivijayan",
      },
      {
        chapterNo: 14,
        section: "Geogebra",
        title: "Transversal",
        author: "Mr.A.Kasivijayan",
      },
      {
        chapterNo: 15,
        section: "Geogebra",
        title: "Parts of a Circle",
        author: "Mr.S.Vaitheeswaraprabu",
      },
      {
        chapterNo: 16,
        section: "Geogebra",
        title: "Pi Value",
        author: "Mr.S.Vaitheeswaraprabu",
      },
      {
        chapterNo: 17,
        section: "Coding",
        title: "Turtle Art Introduction",
        author: "Mrs.N.Kalpana",
      },
      {
        chapterNo: 18,
        section: "Coding",
        title: "Turtle Art - Colour blocks",
        author: "Mr.M.Maria Anthuvan",
      },
      {
        chapterNo: 19,
        section: "Coding",
        title: "Turtle Art - Drawing arcs and circles",
        author: "Mr.M.Maria Anthuvan",
      },
      {
        chapterNo: 20,
        section: "Coding",
        title: "Turtle Art - Drawing dotted lines",
        author: "Mr.M.Maria Anthuvan",
      },
      {
        chapterNo: 21,
        section: "Coding",
        title: "Turtle Art - Random block",
        author: "Mr.J.Senthil Selvan",
      },
      {
        chapterNo: 22,
        section: "Coding",
        title: "Turtle Art - Drawing a flower",
        author: "Mr.J.Senthil Selvan",
      },
      {
        chapterNo: 23,
        section: "Coding",
        title: "Turtle Art - Variables",
        author: "Mrs.N.Kalpana",
      },
      {
        chapterNo: 24,
        section: "Coding",
        title: "Turtle Art - If conditional",
        author: "Mr.J.Senthil Selvan",
      },
      {
        chapterNo: 25,
        section: "Coding",
        title: "Turtle Art - Assignment",
        author: "Mr.Anandhakanan",
      },
    ],
  },
  {
    standard: "Class 8",
    chapters: [
      {
        chapterNo: 1,
        section: "Fundamental",
        title: "Power",
        author: "Mr.S. Ganesh",
      },
      {
        chapterNo: 2,
        section: "Fundamental",
        title: "Power",
        author: "Mr.S. Ganesh",
      },
      {
        chapterNo: 3,
        section: "Fundamental",
        title: "Power",
        author: "Mr.J.Senthil Selvan",
      },
      {
        chapterNo: 4,
        section: "Fundamental",
        title: "Power",
        author: "Mr.J.Senthil Selvan",
      },
      {
        chapterNo: 5,
        section: "Online Tools",
        title: "PHET",
        author: "Mr.P.Arikaran",
      },
      {
        chapterNo: 6,
        section: "Online Tools",
        title: "Mapping skill",
        author: "Mr.D.Nagaraj",
      },
      {
        chapterNo: 7,
        section: "AI",
        title: "Image generation",
        author: "PRABHAKAR",
      },
      {
        chapterNo: 8,
        section: "AI",
        title: "Article & Story Creation",
        author: "PRABHAKAR",
      },
      {
        chapterNo: 9,
        section: "AI",
        title: "Mindmap",
        author: "DHILIP",
      },
      {
        chapterNo: 10,
        section: "Geogebra",
        title: "Up Your Data-1",
        author: "DHILIP",
      },
      {
        chapterNo: 11,
        section: "Geogebra",
        title: "Up Your Data-2",
        author: "Mr.S.Vaitheeswaraprabu",
      },
      {
        chapterNo: 12,
        section: "Geogebra",
        title: "Up Your Data-3",
        author: "Mr.S.Kasiraja",
      },
      {
        chapterNo: 13,
        section: "Geogebra",
        title: "Up Your Data-4",
        author: "Mr.S.Vaitheeswaraprabu",
      },
      {
        chapterNo: 14,
        section: "Coding",
        title: "Translator",
        author: "Mr.K.Kumaravelu",
      },
      {
        chapterNo: 15,
        section: "Coding",
        title: "Circular arc",
        author: "Mr.R.Elavarasan",
      },
      {
        chapterNo: 16,
        section: "Coding",
        title: "Sector",
        author: "Mr.R.Elavarasan",
      },
      {
        chapterNo: 17,
        section: "Coding",
        title: "Combined diagram",
        author: "Mr.R.Elavarasan",
      },
      {
        chapterNo: 18,
        section: "Coding",
        title: "3D Shapes",
        author: "Mr.R.Elavarasan",
      },
      {
        chapterNo: 19,
        section: "Coding",
        title: "Plotting",
        author: "Mr.S.Manohar",
      },
      {
        chapterNo: 20,
        section: "Coding",
        title: "Scratch",
        author: "Mr.S.Manohar",
      },
      {
        chapterNo: 21,
        section: "Coding",
        title: "Scratch",
        author: "Mr.S.Manohar",
      },
      {
        chapterNo: 22,
        section: "Coding",
        title: "Scratch",
        author: "Mr.K.Iyyappan",
      },
      {
        chapterNo: 23,
        section: "Coding",
        title: "Scratch",
        author: "Mr.K.Iyyappan",
      },
      {
        chapterNo: 24,
        section: "Coding",
        title: "Scratch",
        author: "Mr.K.Iyyappan",
      },
      {
        chapterNo: 25,
        section: "Coding",
        title: "Scratch",
        author: "Mr.R.Elavarasan",
      },
    ],
  },
  {
    standard: "Class 9",
    chapters: [
      {
        chapterNo: 1,
        section: "Fundamental",
        title: "Impress Your Audience-1",
        author: "Mr.S. Ganesh",
      },
      {
        chapterNo: 2,
        section: "Fundamental",
        title: "Impress Your Audience-2",
        author: "Mr.S. Ganesh",
      },
      {
        chapterNo: 3,
        section: "Fundamental",
        title: "Impress Your Audience-3",
        author: "Mr.S. Ganesh",
      },
      {
        chapterNo: 4,
        section: "Fundamental",
        title: "Impress Your Audience-4",
        author: "Mr.S. Ganesh",
      },
      {
        chapterNo: 5,
        section: "Online Tools",
        title: "Virtual Tour",
        author: "Mr.D.Nagaraj",
      },
      {
        chapterNo: 6,
        section: "Online Tools",
        title: "Periodic Table",
        author: "Mr.P.Arikaran",
      },
      {
        chapterNo: 7,
        section: "AI",
        title: "Powerpoint Presentation",
        author: "PRABHAKAR",
      },
      {
        chapterNo: 8,
        section: "AI",
        title: "VIDEO CREATION",
        author: "DHILIP",
      },
      {
        chapterNo: 9,
        section: "Geogebra",
        title: "Pythagoras Theorem",
        author: "Mr.K.Kumaravelu",
      },
      {
        chapterNo: 10,
        section: "Geogebra",
        title: "Property of Chord of a Circle",
        author: "Mr.S.Vaitheeswaraprabu",
      },
      {
        chapterNo: 11,
        section: "Geogebra",
        title: "Circumcentre",
        author: "Mr.S.Vaitheeswaraprabu",
      },
      {
        chapterNo: 12,
        section: "Geogebra",
        title: "Graph of a Equation",
        author: "Mr.K.Kumaravelu",
      },
      {
        chapterNo: 13,
        section: "Coding",
        title: "Vex Stimulations",
        author: "Mr.Jaffer",
      },
      {
        chapterNo: 14,
        section: "Coding",
        title: "Vex Stimulations",
        author: "Mr.Jaffer",
      },
      {
        chapterNo: 15,
        section: "Coding",
        title: "Vex Stimulations",
        author: "Mr.Jaffer",
      },
      {
        chapterNo: 16,
        section: "Coding",
        title: "Python",
        author: "Mr.Thakeer",
      },
      {
        chapterNo: 17,
        section: "Coding",
        title: "Python",
        author: "Mr.Thakeer",
      },
      {
        chapterNo: 18,
        section: "Coding",
        title: "Python",
        author: "Mr.Thakeer",
      },
      {
        chapterNo: 19,
        section: "Coding",
        title: "Python",
        author: "Mr.Thakeer",
      },
      {
        chapterNo: 20,
        section: "Coding",
        title: "Python",
        author: "Mr.Thakeer",
      },
      {
        chapterNo: 21,
        section: "Coding",
        title: "Python",
        author: "Mr.Thakeer",
      },
      {
        chapterNo: 22,
        section: "Coding",
        title: "Python",
        author: "Mr.Thakeer",
      },
      {
        chapterNo: 23,
        section: "Coding",
        title: "Python",
        author: "Mr.Thakeer",
      },
      {
        chapterNo: 24,
        section: "Coding",
        title: "Python",
        author: "Mr.Thakeer",
      },
      {
        chapterNo: 25,
        section: "Coding",
        title: "Python",
        author: "Mr.Thakeer",
      },
    ],
  },
];
